name: "Workflow Kunu"


on:
  push:
    branches: Kunu

jobs:
    build_kunu:
        runs-on: ubuntu-latest
        steps:
            - name: Print something about Workflow
              run:
                    echo "This is a new workflow which gets triggered when something is pushed on Kunu branch"
            - name: Print current date
              run:
                    echo "Current date is $(date)"
            - name: Print current directory
              run:
                    echo "Current directory is $(pwd)"
