name: "Workflow Kunu"


on:
  push:
    branches: 'Kunu'
  pull_request:
      branches: 'master'
  workflow_dispatch:
      
      

jobs:
    runs_on_push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' 
        steps:
            - name: Print something about Workflow when something is pushed on Kunu branch
              run:
                    echo "This is a new workflow which gets triggered when something is pushed on Kunu branch"
            - name: Print current date
              run:
                    echo "Current date is $(date)"
            - name: Print current directory
              run:
                    echo "Current directory is $(pwd)"
    runs_on_pull_request:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Print something about Workflow when pull request is made
              run:
                    echo "This is a new workflow which gets triggered when something is pulled on master branch"
            - name: Print current date
              run:
                    echo "Current date is $(date)"

            
    runs_on_workflow_dispatch:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
            - name: Print something about Workflow when workflow is dispatched
              run:
                    echo "This is a new workflow which gets triggered when workflow is dispatched"
            - name: Print current date
              run:
                    echo "Current date is $(date)"